### PR TITLE
Implement filtering functionality using Tags #13

### LINKED ISSUE #13: Implement filtering functionality using Tags
**User story**
As a user, I want to be able to filter search results based on the selected set of tags so that I am presented with a more concise and on-point list of businesses/volunteers to work with.

**Acceptance criteria**
- Ensure result items(individuals, businesses) have checked tags

### PR DESCRIPTION
**Pull request by yehee**
#### [Implement filtering functionality using Tags](#13)

**Checklist**
- [x] Run `npm run lint:fix` or `yarn lint:fix` on `client` directory

**What and how**
- Store list of `filters` on Redux and filter list of businesses/volunteers upon rendering
- Define `defaultNeeds` and `defaultSkills` on `constant.js`
- Use `npm-run-all` to run client-side application and server in parallel

### CODE REVIEW

**Review by anhyesun — APPROVED** [review]
Looks good. Seems like `src/components/Tags.js` file is not used anymore, so feel free to delete that file. :)

**Comment by yehee** [comment]
> Looks good. Seems like `src/components/Tags.js` file is not used anymore, so feel free to delete that file. :)

I don't think we have `src/components/Tags.js` file, did you mean to say `src/components/Tags/Tags.js`? In that case, we're still referencing that component in `BusinessesList.js` and `VolunteersList.js`.

**Comment by anhyesun** [comment]
I may pull the wrong branch - if so, that's fine!

**Comment by yehee** [comment]
Changes merged to `master` with #69

**Pull request closed without merging**
